export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

# Enable command autocorrection
ENABLE_CORRECTION="true"

plugins=(git)

source $ZSH/oh-my-zsh.sh

# set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

#----------------
# Exports
# ---------------

# Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='vim'
 fi

# Export NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Export zlib (For PHP extensions)
export LDFLAGS="-L/opt/homebrew/opt/zlib/lib"
export CPPFLAGS="-I/opt/homebrew/opt/zlib/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig"

# Export Python version manager
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Export config path
export XDG_CONFIG_HOME="$HOME/.config"

# Add scripts to path
export PATH="$XDG_CONFIG_HOME/bin:$PATH"

# Github CLI
export GH_EDITOR=nvim

#export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
#export VIMDOTDIR="$XDG_CONFIG_HOME/vim"

# -----------------------
# Keybinds
# -----------------------
bindkey -s ^f "tmux-sessioniser\r"

# -----------------------
# Alias
# -----------------------
alias zshconfig="vim ~/.zshrc"
alias sshconfig="vim ~/.ssh/config"
alias reload="source ~/.zshrc"
alias storm="phpstorm1 ."

# PHP Deployer
alias dep='vendor/bin/dep'

# Laravel artisan
alias vap="valet php ./artisan"

# Flush DNS
alias flushdns="sudo killall -HUP mDNSResponder && echo macOS DNS Cache Reset"

# Git
alias gc="git commit -m $1"
alias ga="git add"
alias gs="git status"
alias go="git checkout"
alias gr="git restore --staged"
alias gp="git push"

#export PATH="/Users/mattyforth/.config/herd-lite/bin:$PATH"
#export PHP_INI_SCAN_DIR="/Users/mattyforth/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"
