export DOTFILES="$HOME/.config"
export XDG_CONFIG_HOME="$DOTFILES"

# Load ZSH
export ZSH="$HOME/.oh-my-zsh"
# export TERM="tmux-256color"

ZSH_THEME="robbyrussell"

# Enable command autocorrection
ENABLE_CORRECTION="false"

plugins=(git)

ZSH_CUSTOM="$DOTFILES/zsh"

# set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

source $ZSH/oh-my-zsh.sh

# Setup homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

export EDITOR='nvim'

# Load NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Export zlib (For PHP extensions)
export LDFLAGS="-L/opt/homebrew/opt/zlib/lib"
export CPPFLAGS="-I/opt/homebrew/opt/zlib/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/zlib/lib/pkgconfig"

# Export Python version manager
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Export config path
export RIPGREP_CONFIG_PATH=$XDG_CONFIG_HOME/ripgrep/.ripgreprc

# Github CLI
export GH_EDITOR=nvim

export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
#export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
#export VIMDOTDIR="$XDG_CONFIG_HOME/vim"

#export PATH="/Users/mattyforth/.config/herd-lite/bin:$PATH"
#export PHP_INI_SCAN_DIR="/Users/mattyforth/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"


